version: "3.3"

services:
    wechat-box:
        image: "sureer/wechat-box:3.9.2.23"
        restart: unless-stopped
        container_name: "wechat-box"
        environment:
            WC_AUTO_RESTART: "yes"
        ports:
            - "8080:8080"
        volumes:
              - "./.wechat/WeChat Files/:/home/app/WeChat Files/"
              - "./.wechat/Applcation Data/:/home/app/.wine/drive_c/users/user/Application Data/"
              - "./external:/home/app/external"
        tty: true
